/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package clinicPck;

/**
 *
 * @author AhmedRagab
 */
public class Report extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 770));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 770));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 770));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/report1.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 70, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/patient2.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(504, 20, 80, 80);

        jLabel4.setFont(new java.awt.Font("Nueva Std", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("AG-Soft Clinic");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 30, 230, 50);

        jLabel5.setText("عيادة : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(534, 130, 40, 14);

        jLabel6.setText(".........................");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(424, 130, 100, 14);

        jLabel7.setText("التاريخ :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 130, 40, 14);

        jLabel8.setText(".........................");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 130, 100, 14);

        jLabel9.setText("Date :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 130, 40, 14);

        jLabel10.setText("الي :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(540, 170, 30, 14);

        jLabel11.setText("To :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 170, 30, 14);

        jLabel12.setText("....................................................................................................................");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(70, 170, 450, 14);

        jLabel13.setText("الاسم :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(530, 210, 36, 14);

        jLabel14.setText(".................................................................................................");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(140, 210, 370, 14);

        jLabel15.setText("Name of Patient :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 210, 100, 14);

        jLabel16.setText("رقم الملف الطبي :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(480, 250, 90, 14);

        jLabel17.setText("......................");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(380, 250, 90, 14);

        jLabel18.setText("PIN. No :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(320, 250, 50, 14);

        jLabel19.setText("السن :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(210, 250, 50, 14);

        jLabel21.setText("Age :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(30, 250, 40, 14);

        jLabel20.setText(".............................");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(80, 250, 120, 14);

        jLabel22.setText("تاريخ العرض علي العيادة :");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(450, 290, 120, 14);

        jLabel23.setText("...................................................................");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(200, 290, 240, 14);

        jLabel24.setText("Date Seen As Out/Patient :");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(30, 290, 150, 14);

        jLabel25.setText("التشخيص :");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(510, 330, 60, 14);

        jLabel26.setText("......................................................................................................");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(110, 330, 390, 14);

        jLabel27.setText("Diagnosis :");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(30, 330, 70, 14);

        jLabel28.setText(".......................................................................................................................................");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(30, 360, 540, 14);

        jLabel29.setText("التقرير :");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(530, 400, 36, 14);

        jLabel30.setText("..............................................................................................................");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(100, 400, 420, 14);

        jLabel31.setText("Report :");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(30, 400, 50, 14);

        jLabel32.setText(".......................................................................................................................................");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(30, 430, 540, 14);

        jLabel33.setText(".......................................................................................................................................");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(30, 460, 540, 14);

        jLabel34.setText(".......................................................................................................................................");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(30, 490, 540, 14);

        jLabel35.setText(".......................................................................................................................................");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(30, 520, 540, 14);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(60, 152, 470, 10);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(80, 552, 430, 10);

        jLabel36.setText("التوصية بإجازة مرضية : يحتاج لاجازة مرضية لمدة (                             )");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(250, 580, 320, 14);

        jLabel37.setText("إعتـبــــارا مــــن تـــاريــــــخ :");
        jPanel1.add(jLabel37);
        jLabel37.setBounds(420, 620, 140, 14);

        jLabel38.setText(".....");
        jPanel1.add(jLabel38);
        jLabel38.setBounds(330, 620, 20, 14);

        jLabel39.setText("/");
        jPanel1.add(jLabel39);
        jLabel39.setBounds(320, 620, 10, 14);

        jLabel40.setText(".....");
        jPanel1.add(jLabel40);
        jLabel40.setBounds(290, 620, 20, 14);

        jLabel41.setText("/");
        jPanel1.add(jLabel41);
        jLabel41.setBounds(280, 620, 10, 14);

        jLabel42.setText("........");
        jPanel1.add(jLabel42);
        jLabel42.setBounds(240, 620, 40, 14);

        jLabel43.setText("Recommended  sick  leave  from  :");
        jPanel1.add(jLabel43);
        jLabel43.setBounds(20, 620, 190, 14);

        jLabel44.setText("الطبيب المعالج :");
        jPanel1.add(jLabel44);
        jLabel44.setBounds(490, 670, 80, 14);

        jLabel45.setText("التوقيع :");
        jPanel1.add(jLabel45);
        jLabel45.setBounds(530, 710, 37, 14);

        jLabel46.setText("الختم");
        jPanel1.add(jLabel46);
        jLabel46.setBounds(80, 670, 25, 14);

        jLabel47.setText(".....................................");
        jPanel1.add(jLabel47);
        jLabel47.setBounds(330, 670, 150, 14);

        jLabel48.setText("..............................");
        jPanel1.add(jLabel48);
        jLabel48.setBounds(400, 710, 120, 14);

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/khetm3.png"))); // NOI18N
        jPanel1.add(jLabel49);
        jLabel49.setBounds(30, 700, 110, 60);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
